MAIL_PASSWORD: 'Exchangetendds123.'
MAIL: 'exchangetendds@gmail.com'
NOTIFICATION_EMAIL_PASSWORD: 'Exchangetendds123.'
NOTIFICATION_EMAIL: 'exchangetendds@gmail.com'
BTF_BUYING_PRICE: '2000'
BTF_SELLING_PRICE: '2100'
BTH_BUYING_PRICE: '1500'
BTH_SELLING_PRICE: '1800'
PARTNER_EMAIL: 'profe@uc.cl'
PARTNER_PASSWORD: 'profe123'
PARTNER_PASSWORD_CONFIRMATION: 'profe123'
ADMIN_EMAIL: 'administrador@admin.cl'
ADMIN_PASSWORD: 'Adminpassword1'
ADMIN_PASSWORD_CONFIRMATION: 'Adminpassword1'
CLP_AMOUNT: '10000000'
BTH_AMOUNT: '1000000'
BTF_AMOUNT: '900000'