---
version: "3"
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "8000:3000"
    depends_on:
      - postgresql
    environment:
      DB_HOST: postgresql

  postgresql:
    image: postgres:11.3
    ports:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ""
    volumes:
      - postgresql_data:/var/lib/postgresql/data
volumes:
  postgresql_data:
