require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/cryptocurrencies", type: :request do
  # Cryptocurrency. As you add validations to Cryptocurrency, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip("Add a hash of attributes valid for your model")
  end

  let(:invalid_attributes) do
    skip("Add a hash of attributes invalid for your model")
  end

  describe "GET /index" do
    it "renders a successful response" do
      Cryptocurrency.create! valid_attributes
      get cryptocurrencies_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      cryptocurrency = Cryptocurrency.create! valid_attributes
      get cryptocurrency_url(cryptocurrency)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_cryptocurrency_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      cryptocurrency = Cryptocurrency.create! valid_attributes
      get edit_cryptocurrency_url(cryptocurrency)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Cryptocurrency" do
        expect do
          post cryptocurrencies_url, params: { cryptocurrency: valid_attributes }
        end.to change { Cryptocurrency.count }.by(1)
      end

      it "redirects to the created cryptocurrency" do
        post cryptocurrencies_url, params: { cryptocurrency: valid_attributes }
        expect(response).to redirect_to(cryptocurrency_url(Cryptocurrency.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Cryptocurrency" do
        expect do
          post cryptocurrencies_url, params: { cryptocurrency: invalid_attributes }
        end.to change { Cryptocurrency.count }.by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post cryptocurrencies_url, params: { cryptocurrency: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        skip("Add a hash of attributes valid for your model")
      end

      it "updates the requested cryptocurrency" do
        cryptocurrency = Cryptocurrency.create! valid_attributes
        patch cryptocurrency_url(cryptocurrency), params: { cryptocurrency: new_attributes }
        cryptocurrency.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the cryptocurrency" do
        cryptocurrency = Cryptocurrency.create! valid_attributes
        patch cryptocurrency_url(cryptocurrency), params: { cryptocurrency: new_attributes }
        cryptocurrency.reload
        expect(response).to redirect_to(cryptocurrency_url(cryptocurrency))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        cryptocurrency = Cryptocurrency.create! valid_attributes
        patch cryptocurrency_url(cryptocurrency), params: { cryptocurrency: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested cryptocurrency" do
      cryptocurrency = Cryptocurrency.create! valid_attributes
      expect do
        delete cryptocurrency_url(cryptocurrency)
      end.to change { Cryptocurrency.count }.by(-1)
    end

    it "redirects to the cryptocurrencies list" do
      cryptocurrency = Cryptocurrency.create! valid_attributes
      delete cryptocurrency_url(cryptocurrency)
      expect(response).to redirect_to(cryptocurrencies_url)
    end
  end
end
